/**
 * Canonical campaign catalogue for the current two-hero card slice.
 *
 * The 24 entries through `improvised-theorem` are the locked Card Trial
 * decks (`RAT_KING_LIST` / `OLD_MAN_LIST`) that Arena's PoC lobby still
 * fights with unchanged. The entries after that are build-exclusive signature
 * cards added for character build selection (see
 * `../old-man-builds.ts`) — they are never added to `OLD_MAN_LIST` and never
 * appear in Arena. `reckoning-ward` is Reckoning Strike's defensive twin
 * (same-target consume, but banks Barrier and retreats to Back instead of
 * dealing damage and advancing to Front) — it replaced the Reckoning
 * build's single `brace-for-it` copy (2026-08-29) so consuming Opened is a
 * real choice, not the deck's only line of play; see
 * `docs/design/2026-08-29-old-man-build-selection.md`. That leaves
 * `brace-for-it` implemented and tested but currently unreachable — not in
 * any build starter and not an authored floor reward (see
 * `../campaign-card-rewards.ts`). The next three (`last-litter`,
 * `feed-the-king`, `one-more-rat`) are Rat King sacrifice-mechanic cards
 * built around consuming the singleton Rat. `king's-due` is the Crown
 * payoff used by King of the Heap. The separate six-school catalogue in
 * `six-school-cards.ts` remains deferred experimental material, not
 * campaign authority.
 */

import type { CardDef, CardId, HeroId } from "./types";

export const CARD_DEFS: Record<CardId, CardDef> = {
  nip: {
    id: "nip",
    name: "Nip",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5.",
  },
  "fight-dirty": {
    id: "fight-dirty",
    name: "Fight Dirty",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    draft: "dirty-tricks",
    text: "Reveal 3 Dirty Tricks for the target. Choose 1 and pay its printed cost.",
  },
  brace: {
    id: "brace",
    name: "Brace",
    cost: 1,
    hero: "rat-king",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 6 Barrier.",
  },
  "open-the-rank": {
    id: "open-the-rank",
    name: "Open the Rank",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target.",
  },
  "from-the-dark": {
    id: "from-the-dark",
    name: "From the Dark",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target. Back: if Rat lives, it bites 3.",
  },
  "swarm-the-wound": {
    id: "swarm-the-wound",
    name: "Swarm the Wound",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Deal 5. Consume Opened: deal 4 more to that enemy.",
  },
  "burst-the-nest": {
    id: "burst-the-nest",
    name: "Burst the Nest",
    cost: 2,
    hero: "rat-king",
    target: "single-enemy",
    consume: "splash-others",
    opens: false,
    text: "Deal 8. Consume Opened: deal 4 to every other enemy.",
  },
  litter: {
    id: "litter",
    name: "Litter",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4. If no Rat exists, spawn it on your row.",
  },
  "send-the-rat": {
    id: "send-the-rat",
    name: "Send the Rat",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "If Rat exists, move it to the other row, then it bites 5. If none exists, deal 4 yourself.",
  },
  tide: {
    id: "tide",
    name: "Tide",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4. Gain 2 Barrier. Front: +2 damage.",
  },
  lunge: {
    id: "lunge",
    name: "Lunge",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Move to Front, then deal 5.",
  },
  "king-of-the-heap": {
    id: "king-of-the-heap",
    name: "King of the Heap",
    cost: 2,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 7 +3 Front. Gain 8 Barrier. Crown target.",
  },
  "the-staff-speaks": {
    id: "the-staff-speaks",
    name: "The Staff Speaks",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 6. Hush next intent.",
  },
  "pale-ward": {
    id: "pale-ward",
    name: "Pale Ward",
    cost: 1,
    hero: "old-man",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 7 Barrier.",
  },
  faultline: {
    id: "faultline",
    name: "Faultline",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 5. Open the target.",
  },
  "marrow-divide": {
    id: "marrow-divide",
    name: "Marrow Divide",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target.",
  },
  "full-stop": {
    id: "full-stop",
    name: "Full Stop",
    cost: 2,
    hero: "old-man",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Deal 8. Consume Opened: deal 8 more to that enemy.",
  },
  "sever-the-thread": {
    id: "sever-the-thread",
    name: "Sever the Thread",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "second-enemy",
    opens: false,
    text: "Deal 5. Consume Opened: deal 5 to a second enemy.",
  },
  "the-threshold": {
    id: "the-threshold",
    name: "The Threshold",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Arm an Omen: when the target acts, deal 7 before its intent.",
  },
  "distant-hand": {
    id: "distant-hand",
    name: "Distant Hand",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5. Back: gain 3 Barrier.",
  },
  "parting-word": {
    id: "parting-word",
    name: "Parting Word",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4, then move to Back.",
  },
  unlight: {
    id: "unlight",
    name: "Unlight",
    cost: 2,
    hero: "old-man",
    target: "all-enemies",
    consume: "none",
    opens: false,
    text: "Deal 4 to every enemy.",
  },
  "last-bastion": {
    id: "last-bastion",
    name: "Last Bastion",
    cost: 2,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 8 and gain 9 Barrier. Front: +3 damage.",
  },
  "improvised-theorem": {
    id: "improvised-theorem",
    name: "Improvised Theorem",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    draft: "arcane-responses",
    text: "Reveal 3 Arcane Responses for the target. Choose 1 and pay its printed cost.",
  },

  // --- Old Man build-exclusive signature cards ----------------------------
  // Not part of OLD_MAN_LIST / Arena. Owned only by a campaign save whose
  // Old Man build includes them (see ../old-man-builds.ts).
  "veil-of-quiet": {
    id: "veil-of-quiet",
    name: "Veil of Quiet",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Hush the target's next intent. Gain 3 Barrier.",
  },
  "the-quiet-after": {
    id: "the-quiet-after",
    name: "The Quiet After",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 3. Already Hushed: deal 5 more instead.",
  },
  "silence-the-hall": {
    id: "silence-the-hall",
    name: "Silence the Hall",
    cost: 2,
    hero: "old-man",
    target: "all-enemies",
    consume: "none",
    opens: false,
    text: "Hush every enemy's next intent.",
  },
  "hasten-the-hour": {
    id: "hasten-the-hour",
    name: "Hasten the Hour",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Armed Omen on the target: trigger it, then deal 3. Otherwise, deal 5.",
  },
  "the-final-word": {
    id: "the-final-word",
    name: "The Final Word",
    cost: 2,
    hero: "old-man",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 5 Barrier. Armed Omen: gain 5 more.",
  },
  "reckoning-strike": {
    id: "reckoning-strike",
    name: "Reckoning Strike",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Deal 5. Consume Opened: move to Front and deal 5 more.",
  },
  "reckoning-ward": {
    id: "reckoning-ward",
    name: "Reckoning Ward",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Gain 4 Barrier. Consume Opened: move to Back and gain 6 more.",
  },
  "brace-for-it": {
    id: "brace-for-it",
    name: "Brace for It",
    cost: 2,
    hero: "old-man",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 12 Barrier.",
  },
  "last-litter": {
    id: "last-litter",
    name: "Last Litter",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5. If Rat exists, consume it: deal 8 more.",
  },
  "feed-the-king": {
    id: "feed-the-king",
    name: "Feed the King",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Crown the target. Gain 4 Barrier. If Rat exists, consume it: gain 10 Barrier instead.",
  },
  "one-more-rat": {
    id: "one-more-rat",
    name: "One More Rat",
    cost: 2,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 6. If Rat exists, consume it: deal 6 more and spawn a new Rat on your row.",
  },
  "king's-due": {
    id: "king's-due",
    name: "King's Due",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4. Crowned target: deal 8 instead.",
  },
};

export const RAT_KING_LIST: CardId[] = [
  "nip",
  "fight-dirty",
  "brace",
  "open-the-rank",
  "from-the-dark",
  "swarm-the-wound",
  "burst-the-nest",
  "litter",
  "send-the-rat",
  "tide",
  "lunge",
  "king-of-the-heap",
];

export const OLD_MAN_LIST: CardId[] = [
  "the-staff-speaks",
  "improvised-theorem",
  "pale-ward",
  "faultline",
  "marrow-divide",
  "full-stop",
  "sever-the-thread",
  "the-threshold",
  "distant-hand",
  "parting-word",
  "unlight",
  "last-bastion",
];

export function deckListFor(hero: HeroId): CardId[] {
  return hero === "rat-king" ? [...RAT_KING_LIST] : [...OLD_MAN_LIST];
}

export function cardDef(id: CardId): CardDef {
  return CARD_DEFS[id];
}
