/**
 * Locked 24-card Card Trial decks. Do not add a 25th card.
 */

import type { CardDef, CardId, HeroId } from "./types";

export const CARD_DEFS: Record<CardId, CardDef> = {
  nip: {
    id: "nip",
    name: "Nip",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5.",
  },
  brace: {
    id: "brace",
    name: "Brace",
    cost: 1,
    hero: "rat-king",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 6 Guard.",
  },
  "open-the-rank": {
    id: "open-the-rank",
    name: "Open the Rank",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target.",
  },
  "from-the-dark": {
    id: "from-the-dark",
    name: "From the Dark",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target. Back: if Rat lives, it bites 3.",
  },
  "swarm-the-wound": {
    id: "swarm-the-wound",
    name: "Swarm the Wound",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Deal 5. Consume Opened: deal 4 more to that enemy.",
  },
  "burst-the-nest": {
    id: "burst-the-nest",
    name: "Burst the Nest",
    cost: 2,
    hero: "rat-king",
    target: "single-enemy",
    consume: "splash-others",
    opens: false,
    text: "Deal 8. Consume Opened: deal 4 to every other enemy.",
  },
  litter: {
    id: "litter",
    name: "Litter",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4. If no Rat exists, spawn it on your row.",
  },
  "send-the-rat": {
    id: "send-the-rat",
    name: "Send the Rat",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "If Rat exists, move it to the other row, then it bites 5. If none exists, deal 4 yourself.",
  },
  tide: {
    id: "tide",
    name: "Tide",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5. Front: +3.",
  },
  lunge: {
    id: "lunge",
    name: "Lunge",
    cost: 1,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Move to Front, then deal 5.",
  },
  "king-of-the-heap": {
    id: "king-of-the-heap",
    name: "King of the Heap",
    cost: 2,
    hero: "rat-king",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 7 and gain 8 Guard. Front: +3 damage.",
  },
  staff: {
    id: "staff",
    name: "Staff",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 6.",
  },
  ward: {
    id: "ward",
    name: "Ward",
    cost: 1,
    hero: "old-man",
    target: "none",
    consume: "none",
    opens: false,
    text: "Gain 7 Guard.",
  },
  crack: {
    id: "crack",
    name: "Crack",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 5. Open the target.",
  },
  "split-bone": {
    id: "split-bone",
    name: "Split Bone",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: true,
    text: "Deal 4. Open the target.",
  },
  "full-stop": {
    id: "full-stop",
    name: "Full Stop",
    cost: 2,
    hero: "old-man",
    target: "single-enemy",
    consume: "same-target",
    opens: false,
    text: "Deal 8. Consume Opened: deal 8 more to that enemy.",
  },
  "cut-the-line": {
    id: "cut-the-line",
    name: "Cut the Line",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "second-enemy",
    opens: false,
    text: "Deal 5. Consume Opened: deal 5 to a second enemy.",
  },
  threshold: {
    id: "threshold",
    name: "Threshold",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5. Front: +4.",
  },
  "from-afar": {
    id: "from-afar",
    name: "From Afar",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 5. Back: gain 3 Guard.",
  },
  "parting-blow": {
    id: "parting-blow",
    name: "Parting Blow",
    cost: 1,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 4, then move to Back.",
  },
  extinguish: {
    id: "extinguish",
    name: "Extinguish",
    cost: 2,
    hero: "old-man",
    target: "all-enemies",
    consume: "none",
    opens: false,
    text: "Deal 4 to every enemy.",
  },
  "stand-and-die": {
    id: "stand-and-die",
    name: "Stand and Die",
    cost: 2,
    hero: "old-man",
    target: "single-enemy",
    consume: "none",
    opens: false,
    text: "Deal 8 and gain 9 Guard. Front: +3 damage.",
  },
};

export const RAT_KING_LIST: CardId[] = [
  "nip",
  "nip",
  "brace",
  "open-the-rank",
  "from-the-dark",
  "swarm-the-wound",
  "burst-the-nest",
  "litter",
  "send-the-rat",
  "tide",
  "lunge",
  "king-of-the-heap",
];

export const OLD_MAN_LIST: CardId[] = [
  "staff",
  "staff",
  "ward",
  "crack",
  "split-bone",
  "full-stop",
  "cut-the-line",
  "threshold",
  "from-afar",
  "parting-blow",
  "extinguish",
  "stand-and-die",
];

export function deckListFor(hero: HeroId): CardId[] {
  return hero === "rat-king" ? [...RAT_KING_LIST] : [...OLD_MAN_LIST];
}

export function cardDef(id: CardId): CardDef {
  return CARD_DEFS[id];
}
