#!/bin/bash
G="node ../../../scripts/pixellab-generate.mjs"
$G --description "single length of heavy aged bronze chain hanging straight down, thick oval links, dark bronze metal, ends in a heavy ring at the bottom, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette.png --out cs-chain-01.png
$G --description "hanging bronze censer brazier suspended by three short chains from a ring, wide shallow bronze bowl with a few faint orange embers inside, dark aged bronze, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette.png --out cs-censer-01.png
$G --description "massive square stone counterweight block suspended by two heavy bronze chains attached to its top corners, dark umber basalt block with bronze strap bands, carved weight mark on its face, hangs straight, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 96x96 --palette palette.png --out cs-counterweight-01.png
$G --description "toppled cylindrical stone column drum lying on its side, dark umber basalt with a carved ring ridge, chunks chipped off, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette-stone.png --out ms-drum-01.png
$G --description "small neat stack of three bronze offering bowls with dust and two pebbles beside them, dark aged bronze, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette.png --out ms-bowls-01.png
$G --description "rubble pile of broken dark umber stone blocks and shards, one large cracked ashlar block leaning on smaller debris, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette-stone.png --out ms-rubble-01.png
$G --description "fallen ceremonial processional standard lying at a slight angle, long dark wooden pole with a tattered deep oxblood red banner remnant hanging from its crossbar, bronze finial, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette.png --out ms-standard-01.png
$G --description "standing bronze tripod brazier with burning orange coals and small flame, dark aged bronze bowl on three legs, 16-bit SNES pixel art sprite, hard pixels, limited palette, side view" --size 64x64 --palette palette.png --out ms-brazier-01.png
